security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        users_in_db:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_db
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: /admin
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
